#!/bin/bash
#
# Runs commands in a Docker container.

docker run \
    --detach \
    --tty \
    --name "debian" \
    --mount "type=bind,src=${PWD}/..,dst=/build" \
    --mount "type=bind,src=${PWD},dst=/build/plymouth" \
    "debian:trixie"

docker exec --workdir "/build/plymouth" "debian" "./scripts/setup"
docker exec \
    --workdir "/build/plymouth" \
    --user "$(id --user)" \
    "debian" \
    "./scripts/build-pkgs"
